# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FWtMeYhZIh-cPO3MMVlSKW2bb38DI2B2
"""

import pandas as pd

df = pd.read_csv("https://graphia.app/datasets/Simple_pairwise-London_tube_map.txt", header = None, delimiter='\t')

df

import networkx as nx

!pip install matplotlib
import matplotlib.pyplot as plot

G = nx.from_pandas_edgelist(df, source = 0, target = 1)

plot.figure(figsize=(100, 80))
tmp = nx.kamada_kawai_layout(G)
nx.draw_networkx_nodes(G, tmp, node_color = "black", alpha = 0.5, node_size = 20)
nx.draw_networkx_edges(G, tmp, width = 7, edge_color = "green", alpha = 0.5)
nx.draw_networkx_labels(G, tmp, font_size= 20)
plot.show()

print("кол-во компонент ",nx.number_connected_components(G))

arr = [node for node, degree in G.degree() if degree > 2]
print(*arr)

def l(G):
    max_len = 0
    for node in G:
        path_lengths = nx.shortest_path_length(G, source=node)
        node_max_len = max(path_lengths.values())
        if node_max_len > max_len:
            max_len = node_max_len
    return max_len
print(l(G))